import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/Components/AuthProvider/AuthProvider'
import ReduxProvider from '@/(Redux)/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>


        <ReduxProvider>
          {children}
        </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
